server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    # eureka server url to communicate

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/centifocus/spring-cloud-demo
          searchPaths: .config-repo          # git repository path
          default-label: master               # /{application}/{profile}[/{label}] 如果label没有，则采用default-label          username:
          username:
          password:

  application:
    name: config

