server:
  port: 8888


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    # eureka server url to communicate


# spring-boot-starter-actuator
management:
  security:
     enabled: false


spring:
  # bus 方式
  # 启动时日志：Mapped "{[/bus/refresh],methods=[POST]}"
  # post请求：http://localhost:8762/bus/refresh 导致config server发RefreshRemoteApplicationEvent事件到Bus，Bus再广播业务服务节点。
  # /bus/refresh?destination=customers:** 即刷新customers的所有服务
  # 可以添加@EventListener注解的AckRemoteApplicationEvent和SentApplicationEvent类型到你自己的应用中。
  rabbitmq:
    virtual-host: /DEV
    username: admin
    password: adminjoindata123
    host: 10.10.110.49
    port: 5672

  cloud:
    # RemoteApplicationEvent的子类都是总线事件
    # /bus/refresh端点被请求后，访问/trace端点就可获得trace结果
    bus:
      trace:
        enabled: true

    config:
      server:
        git:
          uri: https://github.com/centifocus/spring-cloud-demo
          searchPaths: .config-repo          # git repository path
          default-label: master               # /{application}/{profile}[/{label}] 如果label没有，则采用default-label          username:
          username:
          password:

  application:
    name: config

