server:
  port: 9921

eureka:
  client:
    serviceUrl:
      defaultZone: http://dns1:9901/eureka/

zuul:
  routes:
    api-hi:
      path: /hi/**
      serviceId: ribbon
    api-oh:
      path: /oh/**
      serviceId: service-oh

spring:
  rabbitmq:
    virtual-host: /UAT
    username: admin
    password: adminjoindata123
    host: 10.10.110.49
    port: 5672

  sleuth:
    sampler:
      percentage: 1.0

  application:
    name: zuul

