server:
  port: 9921

eureka:
  client:
    serviceUrl:
      defaultZone: http://dns1:9901/eureka/

zuul:
  routes:
    api-hi:
      path: /hi/**
      serviceId: ribbon
    api-oh:
      path: /oh/**
      serviceId: feign

spring:
  application:
    name: zuul

