server:
  port: 9902


eureka:
  instance:
    hostname: dns2
    preferIpAddress: true

  client:
    serviceUrl:
      defaultZone: http://dns1:9901/eureka/,http://dns3:9903/eureka/


# hosts中加 127.0.0.1 dns2
spring:
  profiles:
    active: dns2

  application:
    name: eureka