# application-${profile}.yml
---
server:
  port: 9901


eureka:
  instance:
    hostname: dns1

  client:
    serviceUrl:
    # 一个Region可以包含多个Zone
    # Eureka Client也需要指定Zone, Client在向Server获取注册列表时会优先向自己Zone的Eureka发请求，如果自己Zone中的Eureka全挂了才会尝试向其它Zone
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://dns2:9902/eureka/,http://dns3:9903/eureka/
#      region: wangliqiu-region
    prefer-same-zone-eureka: true
#      availability-zones: zone1


# hosts中加 127.0.0.1 dns1, command line加入：--spring.profiles.active=dns1
spring:
  profiles:
    active: dns1
#    include: dns1    # 无条件激活（一定激活）

  application:
    name: eureka



...