server:
  port: 9901


eureka:
  instance:
    hostname: dns1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


# hosts中加 127.0.0.1 dns1
spring:
  profiles:
    include: dns1