server:
  port: 9941


eureka:
  client:
    serviceUrl:
      defaultZone: http://dns1:9901/eureka/    # eureka server url to communicate


# 刷新时，关闭安全验证
management:
  security:
    enabled: false


spring:
  rabbitmq:
    virtual-host: /DEV
    username: admin
    password: adminjoindata123
    host: 10.10.110.49
    port: 5672

  cloud:
    bus:
      trace:
        enabled: true

    config:
      fail-fast: true
      label: master
      profile: DEV
      # uri: http://localhost:8888/         # config server uri   # 不直连的话，从eureka来路由到config server
      discovery:
        enabled: true
        service-id: config



  zipkin:
    base-url: http://localhost:9951

  application:
    name: service-hi





