server:
  port: 8762

eureka:
  client:
    registerWithEureka: true  # omit
    fetchRegistry: true       # omit
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    # eureka server url to communicate

spring:
  # bus 方式  # post请求：http://localhost:8762/bus/refresh  会重载配置
  # /bus/refresh?destination=customers:** 即刷新服务名为customers的所有服务
  rabbitmq:
    virtual-host: /DEV
    username: admin
    password: adminjoindata123
    host: 10.10.110.49
    port: 5672

  cloud:
    config:
      label: master
      profile: DEV
      # uri: http://localhost:8888/         # config server uri   # 不直连的话，从eureka来路由到config server
      discovery:
        enabled: true
        service-id: config

  application:
    name: service-hi


