server:
  port: 8762

eureka:
  client:
    registerWithEureka: true  # omit
    fetchRegistry: true       # omit
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    # eureka server url to communicate

spring:
  application:
    name: service-hi