server:
  port: 8762

eureka:
  client:
    registerWithEureka: true  # omit
    fetchRegistry: true       # omit
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    # eureka server url to communicate

spring:
  cloud:
    config:
      label: master
      profile: DEV
      # uri: http://localhost:8888/         # config server uri   # 不直连的话，从eureka来路由到config server
      discovery:
        enabled: true
        service-id: config

  application:
    name: service-hi