server:
  port: 9952

eureka:
  client:
    serviceUrl:
      defaultZone: http://dns1:9901/eureka/    # eureka server url to communicate

spring:
  application:
    name: service-hi    # 与 service-hi 相同，来测负载均衡