server:
  port: 9962

security.basic.enabled: false


# turbine要通过eureka来获取应用监控/hystrix.stream地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://dns1:9901/eureka/


turbine:
  combineHostPort: false
  # 表明turbine从Eureka server的serviceId列表中获取哪些应用的信息，然后再aggregator
  appConfig: service-oh,service-hi
  # aggregator.clusterConfig会采用此表达式计算clusterName
  # 默认为EurekaInstanceDiscovery的EUREKA_DEFAULT_CLUSTER_NAME_EXPRESSION，即appName，即直接取service-id，clusterConfig要写service-id
  # 设置"'default'"，则aggregator.clusterConfig可以不写，其默认为default（所有服务节点的clusterName默认为default），
  # 设置metadata['cluster']，即取服务节点的eureka.instance.metadata-map.cluster，则要设置aggregator.clusterConfig为相应值
  clusterNameExpression: metadata['cluster']
  aggregator:
    # 指定聚合哪些集群，多个clusterName使用","分割。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
     clusterConfig: cluster1


spring:
  application:
    name: hystrix-turbine