server:
  port: 9931


eureka:
  client:
    serviceUrl:
      defaultZone: http://dns1:9901/eureka/

client:
  ribbon:
    MaxAutoRetries: 1

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true

  zipkin:
    base-url: http://localhost:9951       # zipkin 控制台

  application:
    name: ribbon
