server:
  port: 9931

#
management:
  security:
    enabled: false


eureka:
  instance:
    metadata-map:
      zone: zone1

  client:
    registry-fetch-interval-seconds: 5
    preferSameZoneEureka: true
    serviceUrl:
      defaultZone: http://dns1:9901/eureka/


# HystrixFeignConfiguration中需要该属性才启用HystrixFeign来包装feign接口的方法到hystrixCommand
feign:
  hystrix.enabled: true
  # GZIP compression for Feign
  compression:
    request.enabled: true
    response.enabled: true


# 默认NONE，自定义对应的类的日志层级
logging.level:
  com.wangliqiu.ribbon.service: FULL


spring:
  cloud:
    inetutils:
      # 过滤docker的虚拟ip
      ignoredInterfaces:
        - docker0
        - veth.*

    loadbalancer:
      retry:
        enabled: true

  rabbitmq:
    virtual-host: /UAT
    username: admin
    password: adminjoindata123
    host: 10.10.110.49
    port: 5672

  zipkin:
#    base-url: http://localhost:9951    # 走rabbit就不用指定了
    # 显示指定一下，否则classpath有rabbit，会采用rabbit
    sender:
      type: rabbit

  sleuth:
    sampler:
      percentage: 1.0     # 100%采样，默认10%；PercentageBasedSampler实现

  application:
    name: ribbon



