server:
  port: 8764


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  zipkin:
    base-url: http://localhost:9411       # zipkin 控制台

  application:
    name: ribbon
