server:
  port: 9931

#
management:
  security:
    enabled: false


eureka:
  instance:
    metadata-map:
      zone: zone1
  client:
    preferSameZoneEureka: true
    serviceUrl:
      defaultZone: http://dns1:9901/eureka/


# HystrixFeignConfiguration中需要该属性才启用HystrixFeign来包装feign接口的方法到hystrixCommand
feign:
  hystrix:
    enabled: true


spring:
  cloud:
    inetutils:
      # 过滤docker的虚拟ip
      ignoredInterfaces:
        - docker0
        - veth.*

    loadbalancer:
      retry:
        enabled: true

  zipkin:
    base-url: http://localhost:9951       # zipkin 控制台

  application:
    name: ribbon
