server:
  port: 9931


eureka:
  client:
    serviceUrl:
      defaultZone: http://dns1:9901/eureka/


spring:
  zipkin:
    base-url: http://localhost:9951       # zipkin 控制台

  application:
    name: ribbon
