



service-hi:
  ribbon:
    # Max number of retries on the same server (excluding the first try)
    MaxAutoRetries: 1
    # Max number of next servers to retry (excluding the first server)
    MaxAutoRetriesNextServer: 1
    # Whether all operations can be retried for this client
    OkToRetryOnAllOperations: true
    # Interval to refresh the server list from the source
    ServerListRefreshInterval: 2000
    ###
    ConnectTimeout: 3000
    ReadTimeout: 3000








